name: Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  web-deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: get latest code
      uses: actions/checkout@v3
      
    - name: build
      run: |
        CI=false
        npm install yarn
        yarn build
    
    - name: sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: build/
